openapi: "3.0.0"
info:
  title: Simple API overview
  version: 2.0.0
servers:
  - url: https://app.fpg-ingauge.com
paths:
  /pulse/api/user/authenticateUserUsingLDAP:
    post:
      operationId: authenticateUser
      summary: Authenticate user and get token to make authenticate API calls
      requestBody:
        description: User to authenticate into IN-Gauge
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user'
            examples:
              ingaugeuser:  # <--- example name
                summary: An example of a user payload
                value:
                  # vv Actual payload goes here vv
                  client_id: restapp
                  client_secret: restapp
                  grant_type: password
                  password: 5858ea228cc2edf88721699b2c8638e5
                  platform: 2
                  username: ingaugeuser@gmail.com
      responses:
        '200':
          description: |-
            200 response
          content:
            application/json:
              examples: 
                foo:
                  value:
                    {
                      "versions": [
                        {
                            "status": "CURRENT",
                            "updated": "2011-01-21T11:33:21Z",
                            "id": "v2.0",
                            "links": [
                                {
                                    "href": "http://127.0.0.1:8774/v2/",
                                    "rel": "self"
                                }
                            ]
                        },
                        {
                            "status": "EXPERIMENTAL",
                            "updated": "2013-07-23T11:33:21Z",
                            "id": "v3.0",
                            "links": [
                                {
                                    "href": "http://127.0.0.1:8774/v3/",
                                    "rel": "self"
                                }
                            ]
                        }
                      ]
                    }
        '300':
          description: |-
            300 response
          content:
            application/json: 
              examples: 
                foo:
                  value: |
                   {
                    "versions": [
                          {
                            "status": "CURRENT",
                            "updated": "2011-01-21T11:33:21Z",
                            "id": "v2.0",
                            "links": [
                                {
                                    "href": "http://127.0.0.1:8774/v2/",
                                    "rel": "self"
                                }
                            ]
                        },
                        {
                            "status": "EXPERIMENTAL",
                            "updated": "2013-07-23T11:33:21Z",
                            "id": "v3.0",
                            "links": [
                                {
                                    "href": "http://127.0.0.1:8774/v3/",
                                    "rel": "self"
                                }
                            ]
                        }
                    ]
                   }
components:
  schemas:
    user:
      type: object
      required:
        - client_id
        - client_secret
        - grant_type
        - password
        - platform
        - username
      properties:
        client_id:
          type: string
        client_secret:
          type: string    
        grant_type:
          type: string    
        password:
          type: string    
        platform:
          type: integer
        username:
          type: string        